---

sudo: false
language: python

python:
    - 3.7-dev

matrix:
    include:
        - os: linux
          dist: bionic
        # Disabled since travis does not support python on windows
        # - os: windows

install:
    - pip install -U pylint
    - sudo apt-get install enchant          # needed for pyenchant
    - pip install pyenchant                 # needed for pylint spell checking
    - pip install -U coveralls
    - pip install mkdocs
    - pip install mkdocs-material

git:
    submodules: false

script:
    - python -m unittest test
    - pylint -j 0 --errors-only test.py
    - coverage run --branch test.py
    - coverage report

after_success:
    - coveralls
    - mkdocs gh-deploy

before_deploy:
    - mkdocs build --verbose --clean --strict # Build local version of the docs

# Deploy mkdocs
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: site
    on:
        branch: master
