---

sudo: false
language: python

python:
  - 3.7-dev

os: linux
    dist: bionic
  - windows

install:
  - pip install -U pandas
  - pip install -U pylint

git:
    submodules: false

script:
    - pytest