---

sudo: false
language: python

python:
    - 3.7-dev

matrix:
    include:
        - os: linux
        - dist: bionic
        # Disabled since travis does not support python on windows
        # - os: windows

install:
    - pip install -U pandas
    - pip install -U pylint

git:
    submodules: false

script:
    - python -m unittest test
    - pylint test.py
