site_name: Test project
repo_url: https://github.com/holzkohlengrill/test.git
repo_name: Test project

docs_dir: doc
use_directory_urls: true
theme:
    name: material
    palette:
        primary: "Black"
        accent: "Amber"
    logo:
        icon: "🔧"
    font: false
    language: "en"
    highlightjs: true
#    hljs_style: Dracula
    hljs_languages:
      - yaml

extra:
  social:
    - type: 'github'
      link: 'https://github.com/holzkohlengrill'

#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - extra
  - codehilite:
      linenums: true

nav:
  - Home: index.md                           # Symlink must have a different name than actual file (which we link to)
  - page1: page1.md
  - page2: page2.md
  - page3: page3.md
  - sub:
      subpage: sub/subpage.md
